# +-------------------------+
# | Ã‰tienne <maiste> Marais |
# |     Zola config file    |
# |         (C) MIT         |
# +-------------------------+

# Intel

base_url = "https://maiste.github.io"
title = "Maiste"
description = "Another useless blog you might find useful."

# Options
generate_feed = true
feed_filename = "rss.xml"
compile_sass = true

[markdown]
highlight_code = true
highlight_theme = "css"


[extra]

## Menu {{

[[extra.menu]]
name = "Blog"
url = "/blog"

[[extra.menu]]
name = "Data"
url = "data"

[[extra.menu]]
name = "About"
url = "about"

## }}
